version: '3'

services:
  api:
    build: .\springboot-docker-compose-api
    ports:
    - "9090:9090"
    depends_on:
      - databases

  client:
    build: .\springboot-docker-compose-client
    ports:
      - "8080:8080"
    depends_on:
      - api

  databases:
    container_name: 'databases'
    image: mysql
    volumes:
      - ./mysql/database:/var/lib/mysql
      - ./mysql/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PASSWORD: "password"
      MYSQL_USER: "user"
      MYSQL_DATABASE: "animaldb"
    ports:
    - "3306:3306"